Document: libneurolab
Title: Debian libneurolab Manual
Author: <insert document author here>
Abstract: This manual describes what libneurolab is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libneurolab/libneurolab.sgml.gz

Format: postscript
Files: /usr/share/doc/libneurolab/libneurolab.ps.gz

Format: text
Files: /usr/share/doc/libneurolab/libneurolab.text.gz

Format: HTML
Index: /usr/share/doc/libneurolab/html/index.html
Files: /usr/share/doc/libneurolab/html/*.html

  
